#
# Build and deploy ruby applications
#
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-and-deploy-ruby
spec:
  workspaces: 
    - name: shared-workspace
  tasks:
    # Make sure the right directory's exist
    - name: setup-env
      taskRef:
        name: setup-env
        kind: Task
      workspaces:
        - name: ruby-build
          workspace: shared-workspace
    # Clone repository
    - name: git-clone
      taskRef:
        name: git-clone
        kind: ClusterTask
      params:
        - name: url
          value: https://github.com/tsterk/ror-sample.git
        - name: subdirectory
          value: html
      workspaces:
        - name: output
          workspace: shared-workspace
      runAfter: 
        - setup-env
    # Install gems
    - name: gem-install
      taskRef:
        name: gem-install
        kind: Task
      workspaces:
        - name: ruby-build
          workspace: shared-workspace
      runAfter:
        - git-clone
    # Create a couple of files as dirty hacks
    - name: create-files
      taskRef:
        name: create-files
        kind: Task
      workspaces:
        - name: ruby-build
          workspace: shared-workspace
      runAfter:
        - git-clone
    # Build runtime image
    - name: build-ruby-run
      taskRef:
        name: buildah
        kind: ClusterTask
      params:
        - name: IMAGE
          value: image-registry.openshift-image-registry.svc:5000/hens-ruby-tekton-poc/myapp
        - name: DOCKERFILE
          value: $(workspaces.source.path)/Dockerfile
        - name: CONTEXT
          value: $(workspaces.source.path)
        - name: FORMAT
          value: docker
        - name: TLSVERIFY
          value: "false"
      workspaces:
        - name: source
          workspace: shared-workspace
      runAfter:
        - gem-install
        - create-files
