apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: gem-install
spec:
  steps:
    - name: gem-install
      image: tsterk/ruby:2.7-build
      env:
        - name: GEM_HOME
          value: "$(workspaces.ruby-build.path)/lib"
        - name: BUNDLE_PATH
          value: "$(workspaces.ruby-build.path)/lib"
        - name: BUNDLE_APP_CONFIG
          value: "$(workspaces.ruby-build.path)/lib"
      script: |
        env
        cd $(workspaces.ruby-build.path)/html && bundle install
  workspaces:
    - name: ruby-build