#
# Build and deploy ruby applications
#
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-and-deploy-ruby
spec:
  workspaces: 
    - name: shared-workspace
  params:
    - name: NAMESPACE
      type: string
      description: Namespace where the pipeline runs
    - name: NAME
      type: string
      description: Name of the app
    - name: TAG
      type: string
      description: Tag of the image
      default: "latest"
    - name: RUBY_VERSION
      type: string
      description: Which version of Ruby to use
      default: "2.7"
    - name: GIT_URL
      type: string
      description: Git url to clone
      default: "https://github.com/sclorg/ruby-ex.git"
  tasks:
    # Make sure the right directory's exist and everything is clean
    - name: setup-env
      taskRef:
        name: setup-env
        kind: Task
      workspaces:
        - name: ruby-build
          workspace: shared-workspace
    # Clone repository
    - name: git-clone
      taskRef:
        name: git-clone
        kind: ClusterTask
      params:
        - name: url
          value: $(params.GIT_URL)
        - name: subdirectory
          value: html
      workspaces:
        - name: output
          workspace: shared-workspace
      runAfter: 
        - setup-env
    # Run bundle install in build container
    - name: gem-install
      taskRef:
        name: gem-install
        kind: Task
      params:
        - name: RUBY_VERSION
          value: $(params.RUBY_VERSION)
      workspaces:
        - name: ruby-build
          workspace: shared-workspace
      runAfter:
        - git-clone
    # Create a couple of files as dirty hacks
    - name: create-files
      taskRef:
        name: create-files
        kind: Task
      params:
        - name: RUBY_VERSION
          value: $(params.RUBY_VERSION)        
      workspaces:
        - name: ruby-build
          workspace: shared-workspace
      runAfter:
        - git-clone
    # Build runtime image
    - name: build-ruby-run
      taskRef:
        name: buildah
        kind: ClusterTask
      params:
        - name: IMAGE
          value: image-registry.openshift-image-registry.svc:5000/$(params.NAMESPACE)/$(params.NAME):$(params.TAG)
        - name: DOCKERFILE
          value: $(workspaces.source.path)/Dockerfile
        - name: CONTEXT
          value: $(workspaces.source.path)
        - name: FORMAT
          value: docker
        - name: TLSVERIFY
          value: "false"
      workspaces:
        - name: source
          workspace: shared-workspace
      runAfter:
        - gem-install
        - create-files
