apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: gem-install
spec:
  params:
    - name: RUBY_VERSION
      description: Which version of Ruby to use
      type: string  
  steps:
    - name: gem-install
      image: tsterk/ruby:$(params.RUBY_VERSION)-build
      env:
        - name: GEM_HOME
          value: "$(workspaces.ruby-build.path)/lib"
        - name: BUNDLE_PATH
          value: "$(workspaces.ruby-build.path)/lib"
        - name: BUNDLE_APP_CONFIG
          value: "$(workspaces.ruby-build.path)/lib"
      script: |
        cd $(workspaces.ruby-build.path)/html && bundle install && gem install rack
  workspaces:
    - name: ruby-build