apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: setup-env
spec:
  steps:
    - name: cleanup-pvc
      image: npohosting/base:3.11
      script: |
        if [ -d $(workspaces.ruby-build.path)/html ]; 
        then
          rm -rf $(workspaces.ruby-build.path)/html
        fi

        if [ -d $(workspaces.ruby-build.path)/lib ];
        then
          rm -rf $(workspaces.ruby-build.path)/lib
        fi

        if [ -f $(workspaces.ruby-build.path)/Dockerfile ];
        then
          rm -rf $(workspaces.ruby-build.path)/Dockerfile
        fi
    - name: create-dir
      image: npohosting/base:3.11
      script: |
        mkdir -v $(workspaces.ruby-build.path)/html
        mkdir -v $(workspaces.ruby-build.path)/lib
  workspaces:
    - name: ruby-build