apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: create-files
spec:
  params:
    - name: RUBY_VERSION
      description: Which version of Ruby to use
      type: string
  steps:
    - name: startfile
      image: npohosting/base:3.11
      script: |
        cat <<EOF >$(workspaces.ruby-build.path)/run-app
        #!/bin/sh

        exec rackup -p /tmp/rack-custom.pid --host 0.0.0.0 --port 3000
        EOF

        chmod a+x $(workspaces.ruby-build.path)/run-app
    - name: dockerfile
      image: npohosting/base:3.11
      script: |
        cat <<EOF >$(workspaces.ruby-build.path)/Dockerfile
        FROM tsterk/ruby:$(params.RUBY_VERSION)-run

        COPY html/ /var/www/html
        COPY lib/ /var/www/lib
        COPY run-app /tmp/
        EOF
  workspaces:
    - name: ruby-build